sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master
  - release
  - tip
matrix:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go tool vet .
  - go test -v -race ./...
